export const Main_Data=[
    {
        cityName:'Bangalore',
        cityid:1,
        hotels:[
            {
                name:'Lemon Tree Premier',
                hotelid:1,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:8.3,
                freecancellation:true,
                images:["https://akm-img-a-in.tosshub.com/sites/btmt/images/stories/lemon_tree_505_120121055322.jpg?size=1200:675",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],

                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Holiday Inn Express & Suites Bengaluru Old Madras Road',
                hotelid:2,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'5000',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'0.0 km from center',
                rating:9,
                freecancellation:true,
                images:["https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_433,q_auto,w_680/itemimages/34/81/3481056_v1.jpeg",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'
            },
            {
                name:'Citrus Cunnigham Road',
                hotelid:3,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'13881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:4,
                distancefromcenter:'2 km from center',
                rating:8.4,
                freecancellation:true,
                images:["https://pix10.agoda.net/hotelImages/625/625255/625255_16091909500046596342.jpg?s=680x433",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                        Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                        Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                        checkin:'12:00',
                        checkout:'11:30'

            },
            {
                name:'The Leela Palace',
                hotelid:4,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'6 km from center',
                rating:8.9,
                freecancellation:true,
                images:["https://www.theleela.com/en_us/bengaluru-hotel-images/offers-and-more/bengalur-garden-view-unlock-happiness.JPG",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Hotel Iris',
                hotelid:5,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:7,
                freecancellation:false,
                images:["https://gos3.ibcdn.com/58a383a2f8ad11e5a8a5001ec9b85d13.png",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            }
        ]
    },
    {
        cityName:'New Delhi',
        cityid:1,
        hotels:[
            {
                name:'Lemon Tree Premier',
                hotelid:1,
                prices:[{price:'10000',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'13450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:8.3,
                freecancellation:true,
                images:["https://akm-img-a-in.tosshub.com/sites/btmt/images/stories/lemon_tree_505_120121055322.jpg?size=1200:675",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],

                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Holiday Inn Express & Suites Bengaluru Old Madras Road',
                hotelid:2,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'5000',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'0.0 km from center',
                rating:9,
                freecancellation:true,
                images:["https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_433,q_auto,w_680/itemimages/34/81/3481056_v1.jpeg",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'
            },
            {
                name:'Citrus Cunnigham Road',
                hotelid:3,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'13881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:4,
                distancefromcenter:'2 km from center',
                rating:8.4,
                freecancellation:true,
                images:["https://pix10.agoda.net/hotelImages/625/625255/625255_16091909500046596342.jpg?s=680x433",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                        Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                        Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                        checkin:'12:00',
                        checkout:'11:30'

            },
            {
                name:'The Leela Palace',
                hotelid:4,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'6 km from center',
                rating:8.9,
                freecancellation:true,
                images:["https://www.theleela.com/en_us/bengaluru-hotel-images/offers-and-more/bengalur-garden-view-unlock-happiness.JPG",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Hotel Iris',
                hotelid:5,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:7,
                freecancellation:false,
                images:["https://gos3.ibcdn.com/58a383a2f8ad11e5a8a5001ec9b85d13.png",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            }
        ]
    },
    {
        cityName:'Luckhnow',
        cityid:1,
        hotels:[
            {
                name:'Lemon Tree Premier',
                hotelid:1,
                prices:[{price:'6000',site_name:'Agoda'},
                       {price:'7000',site_name:'Holday Inn'},
                       {price:'5000',site_name:'Bookking.com'},
                       {price:'7000',site_name:'Make My Trip'},
                       {price:'6000',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:8.3,
                freecancellation:true,
                images:["https://akm-img-a-in.tosshub.com/sites/btmt/images/stories/lemon_tree_505_120121055322.jpg?size=1200:675",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],

                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Holiday Inn Express & Suites Bengaluru Old Madras Road',
                hotelid:2,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'5000',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'0.0 km from center',
                rating:9,
                freecancellation:true,
                images:["https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_433,q_auto,w_680/itemimages/34/81/3481056_v1.jpeg",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'
            },
            {
                name:'Citrus Cunnigham Road',
                hotelid:3,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'13881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:4,
                distancefromcenter:'2 km from center',
                rating:8.4,
                freecancellation:true,
                images:["https://pix10.agoda.net/hotelImages/625/625255/625255_16091909500046596342.jpg?s=680x433",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'The Leela Palace',
                hotelid:4,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'6 km from center',
                rating:8.9,
                freecancellation:true,
                images:["https://www.theleela.com/en_us/bengaluru-hotel-images/offers-and-more/bengalur-garden-view-unlock-happiness.JPG",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Hotel Iris',
                hotelid:5,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:7,
                freecancellation:false,
                images:["https://gos3.ibcdn.com/58a383a2f8ad11e5a8a5001ec9b85d13.png",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            }
        ]
    },
    {
        cityName:'Pune',
        cityid:1,
        hotels:[
            {
                name:'Lemon Tree Premier',
                hotelid:1,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:8.3,
                freecancellation:true,
                images:["https://akm-img-a-in.tosshub.com/sites/btmt/images/stories/lemon_tree_505_120121055322.jpg?size=1200:675",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],

                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Holiday Inn Express & Suites Bengaluru Old Madras Road',
                hotelid:2,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'5000',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'0.0 km from center',
                rating:9,
                freecancellation:true,
                images:["https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_433,q_auto,w_680/itemimages/34/81/3481056_v1.jpeg",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'
            },
            {
                name:'Citrus Cunnigham Road',
                hotelid:3,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'13881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:4,
                distancefromcenter:'2 km from center',
                rating:8.4,
                freecancellation:true,
                images:["https://pix10.agoda.net/hotelImages/625/625255/625255_16091909500046596342.jpg?s=680x433",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'The Leela Palace',
                hotelid:4,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'6 km from center',
                rating:8.9,
                freecancellation:true,
                images:["https://www.theleela.com/en_us/bengaluru-hotel-images/offers-and-more/bengalur-garden-view-unlock-happiness.JPG",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Hotel Iris',
                hotelid:5,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:7,
                freecancellation:false,
                images:["https://gos3.ibcdn.com/58a383a2f8ad11e5a8a5001ec9b85d13.png",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            }
        ]
    },
    {
        cityName:'Manali',
        cityid:1,
        hotels:[
            {
                name:'Lemon Tree Premier',
                hotelid:1,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:8.3,
                freecancellation:true,
                images:["https://akm-img-a-in.tosshub.com/sites/btmt/images/stories/lemon_tree_505_120121055322.jpg?size=1200:675",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],

                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Holiday Inn Express & Suites Bengaluru Old Madras Road',
                hotelid:2,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'5000',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'0.0 km from center',
                rating:9,
                freecancellation:true,
                images:["https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_433,q_auto,w_680/itemimages/34/81/3481056_v1.jpeg",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'
            },
            {
                name:'Citrus Cunnigham Road',
                hotelid:3,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'13881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:4,
                distancefromcenter:'2 km from center',
                rating:8.4,
                freecancellation:true,
                images:["https://pix10.agoda.net/hotelImages/625/625255/625255_16091909500046596342.jpg?s=680x433",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'The Leela Palace',
                hotelid:4,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'6 km from center',
                rating:8.9,
                freecancellation:true,
                images:["https://www.theleela.com/en_us/bengaluru-hotel-images/offers-and-more/bengalur-garden-view-unlock-happiness.JPG",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Hotel Iris',
                hotelid:5,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:7,
                freecancellation:false,
                images:["https://gos3.ibcdn.com/58a383a2f8ad11e5a8a5001ec9b85d13.png",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            }
        ]
    },
    {
        cityName:'Chennai',
        cityid:1,
        hotels:[
            {
                name:'Lemon Tree Premier',
                hotelid:1,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:8.3,
                freecancellation:true,
                images:["https://akm-img-a-in.tosshub.com/sites/btmt/images/stories/lemon_tree_505_120121055322.jpg?size=1200:675",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],

                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Holiday Inn Express & Suites Bengaluru Old Madras Road',
                hotelid:2,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'5000',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'0.0 km from center',
                rating:9,
                freecancellation:true,
                images:["https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_433,q_auto,w_680/itemimages/34/81/3481056_v1.jpeg",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'
            },
            {
                name:'Citrus Cunnigham Road',
                hotelid:3,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'13881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:4,
                distancefromcenter:'2 km from center',
                rating:8.4,
                freecancellation:true,
                images:["https://pix10.agoda.net/hotelImages/625/625255/625255_16091909500046596342.jpg?s=680x433",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'The Leela Palace',
                hotelid:4,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'6 km from center',
                rating:8.9,
                freecancellation:true,
                images:["https://www.theleela.com/en_us/bengaluru-hotel-images/offers-and-more/bengalur-garden-view-unlock-happiness.JPG",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Hotel Iris',
                hotelid:5,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:7,
                freecancellation:false,
                images:["https://gos3.ibcdn.com/58a383a2f8ad11e5a8a5001ec9b85d13.png",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            }
        ]
    },
    {
        cityName:'Chandigarh',
        cityid:1,
        hotels:[
            {
                name:'Lemon Tree Premier',
                hotelid:1,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:8.3,
                freecancellation:true,
                images:["https://akm-img-a-in.tosshub.com/sites/btmt/images/stories/lemon_tree_505_120121055322.jpg?size=1200:675",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],

                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Holiday Inn Express & Suites Bengaluru Old Madras Road',
                hotelid:2,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'5000',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'0.0 km from center',
                rating:9,
                freecancellation:true,
                images:["https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_433,q_auto,w_680/itemimages/34/81/3481056_v1.jpeg",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'
            },
            {
                name:'Citrus Cunnigham Road',
                hotelid:3,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'13881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:4,
                distancefromcenter:'2 km from center',
                rating:8.4,
                freecancellation:true,
                images:["https://pix10.agoda.net/hotelImages/625/625255/625255_16091909500046596342.jpg?s=680x433",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'The Leela Palace',
                hotelid:4,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:5,
                distancefromcenter:'6 km from center',
                rating:8.9,
                freecancellation:true,
                images:["https://www.theleela.com/en_us/bengaluru-hotel-images/offers-and-more/bengalur-garden-view-unlock-happiness.JPG",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            },
            {
                name:'Hotel Iris',
                hotelid:5,
                prices:[{price:'14741',site_name:'Agoda'},
                       {price:'19819',site_name:'Holday Inn'},
                       {price:'20881',site_name:'Bookking.com'},
                       {price:'15450',site_name:'Make My Trip'},
                       {price:'14900',site_name:'Go Ibibo'}
                    ],
                star:3,
                distancefromcenter:'1.4 km from center',
                rating:7,
                freecancellation:false,
                images:["https://gos3.ibcdn.com/58a383a2f8ad11e5a8a5001ec9b85d13.png",
                       'https://www.lemontreehotels.com/getattachment/6c24dd12-ba2f-46f5-afc9-4daa4db4ae65/Executive-Room.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/3c7b070b-4d97-43dc-bdc3-a5fc8efb145a/alligator.aspx?width=680&height=433',
                       'https://www.lemontreehotels.com/getattachment/e3ca52e1-700d-4f78-b9ac-74533186a208/Swimming-Pool.aspx?width=680&height=433',
                        'https://www.lemontreehotels.com/getattachment/e7dedf6e-79bb-450a-a83f-4f799efe38eb/deer.aspx?width=680&height=433'],
                        ratingreview:'A good hotel with all the basic amenities and great helping staffs. Good room service. Although, buffet doesnt provide much options but whatever food items we ordered were of great taste. It is situated on small hill top, hence, you get clear and great sunrise and sunset views.',
                Amenities:{wifiinroom:false,wifiinlobby:true,pool:true,spa:false,parking:true,pets:true,ac:true,gym:false},
                Description1:'this 4-storied hotel is a beautiful combination of traditional grandeur and modern facilities. The 255 exclusive guest rooms are furnished with a range of modern amenities such as television and internet access. International direct-dial phone and safe are also available in any of these rooms.',
                checkin:'12:00',
                checkout:'11:30'

            }
        ]
    }
    
        
    
];

export const populardestination=[
    {Name:'New Delhi',city:'City - Uttar Pradesh, India, Asia'},
    {Name:'Bangalore',city:'City - Karnatka, India, Asia'},
    {Name:'Pune',city:'City - Maharastra, India, Asia'},
    {Name:'Chennai',city:'City - Tamil Nadu, India, Asia'},
    {Name:'Manali',city:'City - Himachal Pradesh, India, Asia'},
    {Name:'Luckhnow',city:'City - Uttar Pradesh, India, Asia'},
    {Name:'Chandigarh',city:'City - Punjab, India, Asia'}

]
export const citylist=[{Name:'Luckhnow',city:'City - Uttar Pradesh, India, Asia'},
{Name:'New Delhi',city:'City - New Delhi, India, Asia'},
{Name:'Bangalore',city:'City - Karnatka, India, Asia'},
{Name:'Pune',city:'City - Pune, India, Asia'},
{Name:'Chennai',city:'City - Chennai, India, Asia'},
{Name:'Manali',city:'City - Himachal Pradesh, India, Asia'},
{Name:'Shimla',city:'City - Himachal Pradesh, India, Asia'},
{Name:'Jaipur',city:'City - Rajashthan, India, Asia'},
{Name:'Goa',city:'City - Goa, India, Asia'},
{Name:'Bihar',city:'City - Bihar, India, Asia'},
{Name:'Kashmir',city:'City - Jammu Kashmir, India, Asia'},
{Name:'Assam',city:'City - Assam, India, Asia'},
{Name:'Arunachal',city:'City - Arunachal, India, Asia'},
{Name:'Shimla',city:'City - Uttar Pradesh, India, Asia'}
]
export const language_list =[{language:'Arabic',text:'العربية'},
{language:'Azerbaijani',text:'Azərbaycanca'},
{language:'English',text:'English'},
{language:'Spanish',text:'Español'},
{language:'French',text:'Français'},
{language:'Hungarian',text:'magyar'},
{language:'Italian',text:'Italiano'},
{language:'Japanese',text:'日本語'},
{language:'Korean',text:'한국어'},
{language:'Arabic',text:'العربية'},
{language:'Azerbaijani',text:'Azərbaycanca'},
{language:'English',text:'English'},
{language:'Spanish',text:'Español'},
{language:'French',text:'Français'},
{language:'Hungarian',text:'magyar'},
{language:'Italian',text:'Italiano'},
{language:'Japanese',text:'日本語'},
{language:'Korean',text:'한국어'},]
export const Distance=[{unit:'Kilometers',length:'Metric'},
{unit:'miles',length:'Imperial'},]